branches:
  except:
    - /^v\d+\.\d+\.\d+$/
services:
  - mongodb
language: node_js
node_js:
  - "8.2.1"
sudo: required
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - nginx
cache:
  directories:
    - node_modules
before_install:
  - nginx -c `pwd`/etc/nginx.conf
  - npm config set spin false
  - npm install -g ember-cli@2.9.1
  - npm install -g bower
  - npm install -g codeclimate-test-reporter
install:
  - npm i .
script:
  - npm run cover
after_success:
  - npm run export
  - codeclimate-test-reporter < coverage/lcov.info
  - npm run semantic-release
