#!/usr/bin/env node
process.env.NODE_ENV = process.argv.indexOf('-p') > -1 || process.argv.indexOf('--production') > -1 ? 'production' : 'development';

if (__dirname.indexOf('Development') > -1) {
	require('babel-register')({
		babelrc: false,
		plugins: [
			'babel-plugin-transform-koaton-es6-modules'
		]
	});
	require('./src');
} else {
	require('./index');
}
