#!/usr/bin/env node
process.env.NODE_ENV = process.argv.indexOf('-p') > -1 || process.argv.indexOf('--production') > -1 ? 'production' : 'development';
process.env.port = parseInt(process.argv[process.argv.indexOf('--port') + 1], 10) || 62626;

require('./lib');
