export default {
	'af': 'Afrikaans',
	'sq': 'Albanian',
	'am': 'Amharic',
	'ar': 'Arabic',
	'hy': 'Armenian',
	'az': 'Azerbaijani',
	'eu': 'Basque',
	'be': 'Belarusian',
	'bn': 'Bengali',
	// 'bo': 'Tibetan',
	'bs': 'Bosnian',
	// 'br': 'Breton',
	'bg': 'Bulgarian',
	'my': 'Burmese',
	'ca': 'Catalan; Valencian',
	'cs': 'Czech',
	// 'ch': 'Chamorro',
	// 'zh': 'Chinese',
	'cy': 'Welsh',
	'da': 'Danish',
	'de': 'German',
	'nl': 'Dutch; Flemish',
	// 'dz': 'Dzongkha',
	'el': 'Greek, Modern (1453-)',
	'en': 'English',
	'eo': 'Esperanto',
	'et': 'Estonian',
	// 'fo': 'Faroese',
	'fa': 'Persian',
	'fi': 'Finnish',
	'fr': 'French',
	'ka': 'Georgian',
	'ga': 'Irish',
	'gl': 'Galician',
	'gu': 'Gujarati',
	'ht': 'Haitian; Haitian Creole',
	// 'he': 'Hebrew',
	'hi': 'Hindi',
	'hr': 'Croatian',
	'hu': 'Hungarian',
	'is': 'Icelandic',
	'id': 'Indonesian',
	'it': 'Italian',
	'ja': 'Japanese',
	// 'kl': 'Kalaallisut; Greenlandic',
	'kn': 'Kannada',
	'kk': 'Kazakh',
	'km': 'Central Khmer',
	// 'rw': 'Kinyarwanda',
	'ko': 'Korean',
	'ku': 'Kurdish',
	'lo': 'Lao',
	'la': 'Latin',
	'lv': 'Latvian',
	'lt': 'Lithuanian',
	'lb': 'Luxembourgish; Letzeburgesch',
	'mk': 'Macedonian',
	'ml': 'Malayalam',
	'mi': 'Maori',
	'mr': 'Marathi',
	'mg': 'Malagasy',
	'mn': 'Mongolian',
	'ne': 'Nepali',
	// 'nn': 'Norwegian Nynorsk; Nynorsk, Norwegian',
	// 'nb': 'Bokmål, Norwegian; Norwegian Bokmål',
	'no': 'Norwegian',
	'ny': 'Chichewa; Chewa; Nyanja',
	// 'pa': 'Panjabi; Punjabi',
	'pl': 'Polish',
	'pt': 'Portuguese',
	'ps': 'Pushto; Pashto',
	// 'qu': 'Quechua',
	// 'rm': 'Romansh',
	'ro': 'Romanian; Moldavian; Moldovan',
	// 'rn': 'Rundi',
	'ru': 'Russian',
	'si': 'Sinhala; Sinhalese',
	'sk': 'Slovak',
	'sl': 'Slovenian',
	'sm': 'Samoan',
	'sn': 'Shona',
	'so': 'Somali',
	'st': 'Sotho, Southern',
	'es': 'Spanish; Castilian',
	'sr': 'Serbian',
	'sw': 'Swahili',
	'sv': 'Swedish',
	'ta': 'Tamil',
	'te': 'Telugu',
	'tl': 'Tagalog',
	'th': 'Thai',
	// 'ti': 'Tigrinya',
	// 'to': 'Tonga (Tonga Islands)',
	// 'tk': 'Turkmen',
	'tr': 'Turkish',
	'uk': 'Ukrainian',
	'ur': 'Urdu',
	'uz': 'Uzbek',
	'vi': 'Vietnamese',
	// 'wo': 'Wolof',
	'xh': 'Xhosa',
	'yi': 'Yiddish',
	'yo': 'Yoruba',
	'zu': 'Zulu'
};
